/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BooksImport } from './routes/Books'
import { Route as AuthorsImport } from './routes/Authors'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const BooksRoute = BooksImport.update({
  id: '/Books',
  path: '/Books',
  getParentRoute: () => rootRoute,
} as any)

const AuthorsRoute = AuthorsImport.update({
  id: '/Authors',
  path: '/Authors',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Authors': {
      id: '/Authors'
      path: '/Authors'
      fullPath: '/Authors'
      preLoaderRoute: typeof AuthorsImport
      parentRoute: typeof rootRoute
    }
    '/Books': {
      id: '/Books'
      path: '/Books'
      fullPath: '/Books'
      preLoaderRoute: typeof BooksImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Authors': typeof AuthorsRoute
  '/Books': typeof BooksRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Authors': typeof AuthorsRoute
  '/Books': typeof BooksRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Authors': typeof AuthorsRoute
  '/Books': typeof BooksRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Authors' | '/Books'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Authors' | '/Books'
  id: '__root__' | '/' | '/Authors' | '/Books'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorsRoute: typeof AuthorsRoute
  BooksRoute: typeof BooksRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorsRoute: AuthorsRoute,
  BooksRoute: BooksRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Authors",
        "/Books"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Authors": {
      "filePath": "Authors.tsx"
    },
    "/Books": {
      "filePath": "Books.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
